### ISSUE TITLE
Where is the theme function?

### ISSUE THREAD

**Issue by jw3126** [JuliaPlots/PlotThemes.jl#10]
This package used to work for me, but now it seems that it doesn't have a `theme`/`plot_theme` function any more? Was this moved to some other package or is there a new selection mechanism?

**Comment by pkofod** [comment]
Hm, it works for me. What is your `Pkg.status`?

**Comment by jw3126** [comment]
My status is  
- PlotThemes                    0.0.1+             a3b39c26

Even if I browse say the current master of PlotThemes here at github I can't spot a `theme` function?

**Comment by pkofod** [comment]
Right,yes. Your question was where `theme` lives. It's not defined in this package, but in `Plots.jl` https://github.com/tbreloff/Plots.jl/blob/281b92c26234238daa48639809808ad579ed3ba4/src/themes.jl

**Comment by jw3126** [comment]
Thanks, I guess I was using a weird combination of `Plots.jl` and `PlotThemes.jl` versions such that neither had the function.

**Comment by pkofod** [comment]
> Thanks, I guess I was using a weird combination of Plots.jl and PlotThemes.jl versions such that neither had the function.

That is 100% possible. Hope it works now!

**Comment by jw3126** [comment]
Yeah it works, thanks again!

**Comment by tbreloff** [comment]
It's because Tony refused to merge the tags that make themes work. And I
refused to try again, and again.
