### ISSUE TITLE
Adding R's color brewer pallet

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaPlots/PlotThemes.jl#32]
Would you consider adding the R [color brewer pallete](https://www.datanovia.com/en/blog/the-a-z-of-rcolorbrewer-palette/)

e.g. _dark2_ pallete
```julia
dark2 = [
 RGB(([ 27, 158, 119]/255)...),
 RGB(([217,  95,   2]/255)...),
 RGB(([117, 112, 179]/255)...),
 RGB(([231,  41, 138]/255)...),
 RGB(([102, 166,  30]/255)...),
 RGB(([230, 171,   2]/255)...),
 RGB(([166, 118,  29]/255)...),
 RGB(([102, 102, 102]/255)...)
 ]
```
![image](https://user-images.githubusercontent.com/50108075/66298312-bbfa0d80-e8f1-11e9-9e70-65aba6c4f7f9.png)

[see Github source](https://github.com/cran/RColorBrewer/blob/master/R/ColorBrewer.R)

**Comment by mkborregaard** [comment]
The colorbrewer palettes (which have nothing to do with R) are added. `dark2` has been one of the few that was kept out for some time - but this open PR adds them https://github.com/JuliaPlots/PlotUtils.jl/pull/67

**Comment by mkborregaard** [comment]
see also https://docs.juliaplots.org/latest/colors/#colorschemes

**Comment by ohmsweetohm1** [comment]
Thank you!

**Comment by ohmsweetohm1** [comment]
This does not really work:

```julia
using Plots, PlotThemes
clibrary(:colorbrewer)
plot(rand(5, 100)', lw=2, palette=:Dark2)
```
![image](https://user-images.githubusercontent.com/50108075/66306843-0637ba80-e903-11e9-8969-394cf368a6d7.png)

**Comment by ohmsweetohm1** [comment]
Especially 2, 3 and 4 in the above plot.

**Comment by mkborregaard** [comment]
Did you check out that Pull Request I linked?

**Comment by mkborregaard** [comment]
Oh I see it got merged. So this is on master? The colors do look a little off.

**Comment by daschw** [comment]
`palette = palette(:Dark2)` works, but IMO `palette = :Dark2` should also. Not sure what's the issue there, maybe a call to `distinguishable_colors` or something.

**Comment by ohmsweetohm1** [comment]
The problem seems to be in `get_color_palette `which is called by plot when the `palette` argument is supplied.

The following code would produce the correct color palette.

```julia
grad = cgrad(:Dark2)
RGBA{Float64}[grad[z] for z in 1:numcolors]
```

**Comment by ohmsweetohm1** [comment]
`zrng = get_zvalues(numcolors)` produces a weird, unordered list of values between 0 and 1 which may be beneficial if the underlying `cgrad` is ordered in some sense. But in this case it is not.

**Comment by mkborregaard** [comment]
Yes, we had some discussion about how to best add the categorical palettes, as they are something different from color gradients. We ended up agreeing that we could just include them and it would be fine. Looks like that wasn't correct.

**Comment by daschw** [comment]
So, do you think we need a type different from `ColorGradient` for categorical palettes?

**Comment by mkborregaard** [comment]
I think distinguishing between them could be a possibility yes. But a little unsure of the repercussions
