### ISSUE TITLE
Should this be a dependency of Plots?

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/PlotThemes.jl#4]
I could remove the theme stuff from Plots and keep anything theme-related here, re-exporting `PlotThemes.plot_theme` (or maybe just `theme`??) 

Thoughts?

**Comment by tbreloff** [comment]
I'll state the obvious... it would need to be registered.  Also, there's absolutely no pressure, but it might be easier to maintain if you move it to the JuliaPlots org.

**Comment by pkofod** [comment]
I'd be fine with `theme`. We can also tag and move stuff here and reexport if you're :+1: with it (which I guess you are, since you suggested it :)).

**Comment by pkofod** [comment]
I just want to say that some theme names are currently pretty randomly chosen, and I'm not 100% sure on the palettes and gradients in the themes, so it will have to come with a "this package is pretty volatile" warning :)

**Comment by tbreloff** [comment]
Great... I can prepare a PR that does this, and delete the stuff from Plots dev.

> "this package is pretty volatile" warning :)

Heh... it's better than the themes in Plots, so I don't think anyone will complain 

Btw... I love the name `:lime`

**Comment by tbreloff** [comment]
Actually what might be easier is an exchange... some stuff specific to Plots can be moved to Plots, and some "general theme stuff" could be moved into PlotThemes.

The goal would be to allow PlotThemes only depend on PlotUtils, then have Plots depend on PlotThemes and export the `theme` method.  The steps:

- put the `_themes` mapping in PlotThemes... `PlotThemes.add_theme` would add to that.
- `theme` would be in Plots, and would set `PlotUtils._default_gradient` and then do the rest of `set_theme`
- change PlotThemes REQUIRE to depend on PlotUtils
- change Plots REQUIRE to depend on PlotThemes

I'll try it out and report back

**Comment by mkborregaard** [comment]
PlotThemes is a dependency now, so this can be closed, right?
