### ISSUE TITLE
ERROR: Unknown key: colorgradient

### ISSUE THREAD

**Issue by otobrzo** [JuliaPlots/PlotThemes.jl#44]
I have tried to use plots theme and I got this error:

**ERROR: Unknown key: colorgradient**

```
using Plots
theme(:dark)

plot(rand(10)
```

julia 1.0.5
Plots v0.27.1

**Comment by daschw** [comment]
Is this not fixed by updating your packages?

**Comment by otobrzo** [comment]
PlotThemes v1.0.1
Plots v0.27.1

Still the same error..

**Comment by etaMet** [comment]
I am getting the same in
- Julia v1.3.1 with 
- Plots v0.27.1,
- PlotUtils v0.6.2 and 
- PlotThemes v1.0.1

Checking with `PlotUtils.cgradients()` I really lost the `:dark` and the `:juno` color_gradient (of the ones I actually care about).
Not sure where and when that happened.

**Comment by BeastyBlacksmith** [comment]
Note, that the current Plots version is 1.3.3, so there is probably some other package holding it back. Try forcing the version via `pkg>add Plots@1.3.3` to get an error message about where the conflict is.
