### ISSUE TITLE
new breakage in PlotThemes or Plots

### ISSUE THREAD

**Issue by lewisl** [JuliaPlots/PlotThemes.jl#58]
error message: ```ERROR: UndefVarError: theme_palette not defined```

Here is the offending (?) line:
```    co_pal = length(plcols) == 2 ? [theme_palette(thm)[2], theme_palette(thm)[4]] : theme_palette(thm)```

That worked for months and months. Just broke with upgrade to Julia 1.5.2 and Plots v 0.28.4 and PlotThemes v1.0.3.

The name theme_palette is exported so I am stymied.

**Comment by BeastyBlacksmith** [comment]
`Plots v 0.28.4` thats a major downgrade. The current Plots version is 1.6.6

**Comment by lewisl** [comment]
Gosh, you are so right!  I don’t know how that happened. Before I ran the code with the posted error message, I ran “up” at the package manager repl.  It downgraded Plots, which I didn’t request. After your post, I went back and rm’ed Plots and reinstalled, which naturally did nothing. When I tried to force @1.6.6, I got messages that StatsPlots and RecipesBase required older versions of Plots, which was also weird.  So, I rm’ed StatsPlots and RecipesBase. Then I did a forced add Plots@1, which installed 1.6.6 and then the right dependencies for StatsPlots and RecipesBase.

So, all good.  What I don’t understand is how I got into this conflict of dependencies. More of a package manager problem than a Plots or PlotThemes problem.  Don’t know what happened.  Only other minorly unusual factor was installing Julia 1.5.2 in place over 1.5.0 without deleting anything or touching any installed packages.

Thanks for pointing out. I should have caught it.  You can close it—just wonder if you have any thoughts on the dependencies version conflict.
