### ISSUE TITLE
More themes with a white background for publication purposes

### ISSUE THREAD

**Issue by musm** [JuliaPlots/PlotThemes.jl#7]
Lovely themes, would be great to have more themes with a white background since it's hard to include non-white background themes in publications.

**Comment by pkofod** [comment]
I agree. Do you know of any good ones?

**Comment by musm** [comment]
Now I'm just throwing ideas out there. Color brewer has several color schemes that were designed for various needs in mind. Perhaps these could be the basis of some new themes with a white background?
http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3

You may also want to look at: https://stanford.edu/~mwaskom/software/seaborn/index.html
Also http://blog.olgabotvinnik.com/prettyplotlib/ (altough IMO not as nice as the others)

**Comment by pkofod** [comment]
Of course the innermost background colour could be non-white still (as in ggplot)
