### ISSUE TITLE
Deactivate themes/Vanilla theme?

### ISSUE THREAD

**Issue by jw3126** [JuliaPlots/PlotThemes.jl#8]
Say I run `:dark`, but decide that my next plot should not be dark, but just good old vanilla Plots.jl style. Is there currently a way to accomplish this?

**Comment by tbreloff** [comment]
There was before yesterday... I need to add that back.

**Comment by tbreloff** [comment]
Implemented in Plots... master branch:

```julia
julia> using Plots
INFO: Precompiling module Plots.

julia> plot(rand(10))

julia> theme(:dark)

julia> plot(rand(10))

julia> theme(:none)

julia> plot(rand(10))
```
