### ISSUE TITLE
Support properties besides colors

### ISSUE THREAD

**Issue by crbinz** [JuliaPlots/PlotThemes.jl#9]
It seems like this package has changed slightly from the last time I saw it, and it looks like a `PlotTheme` now consists only of colors for the various components (or maybe I'm reading wrong?). Specifying things like line width, gridlines, font sizes, etc. would be very useful.

**Comment by tbreloff** [comment]
Do you have any specific suggestions?

**Comment by crbinz** [comment]
As far as properties? All font sizes, line widths and marker sizes, marker stroke width, default gridlines, and default legend would be a good start. Maybe some of those are out of scope for this package, I don't know.

**Comment by tbreloff** [comment]
Sure. Anything is in scope if it's appropriate to a theme. Just suggest
something.

**Comment by pkofod** [comment]
I am very :+1: for such suggestions, especially for emulating stuff like ggplot. Help is very welcome!

**Comment by daschw** [comment]
Couldn't the PlotTheme type just consist of a `Dict{Symbol, Any}` much like the PLOTS_DEFAULTS Dict? This would allow a theme to handle any Plots attribute in general, or am I missing something?

**Comment by mkborregaard** [comment]
I couldn't see why not, but the implementation in Plots would need to be adjusted.

**Comment by pkofod** [comment]
I'll have a look if I can find the time. I don't believe there was a `PLOTS_DEFAULTS` back when I made this package.

**Comment by daschw** [comment]
fixed by #21
